package pipeline

import (
	"encoding/json"
	"time"
)

// JobSpec holds the configuration for a single pipeline run.
type JobSpec struct {
	ID               string                `json:"id"`
	Name             string                `json:"name"`
	Sources          []SourceSpec          `json:"sources"`
	ValidationRules  []ValidationRuleSpec  `json:"validation_rules"`
	TransformRules   []TransformRuleSpec   `json:"transform_rules"`
	AggregationTypes []AggregationSpec     `json:"aggregation_types"` // Formerly AggregationSpecs
	ExportTargets    []ExportTargetSpec    `json:"export_targets"`
	WorkerPoolSizes  WorkerConfig          `json:"worker_pool_sizes"` // Formerly Workers
}

// WorkerConfig defines worker pool sizes for parallel stages.
type WorkerConfig struct {
	Validation     int `json:"validation"`
	Transformation int `json:"transformation"`
}

// SourceSpec represents an input data source.
type SourceSpec struct {
	ID     string            `json:"id"`
	Type   string            `json:"type"` // "csv", "json", "api"
	Path   string            `json:"path"` // Local path or HTTP URL
	Schema map[string]string `json:"schema"` // Mapping of raw column -> standard field name
}

// ValidationRuleSpec defines the checks to run against data fields.
type ValidationRuleSpec struct {
	Field string `json:"field"`
	Rule  string `json:"rule"`  // "required", "min", "max", "type", "regex"
	Param string `json:"param"` // E.g., "0" for min, "float" for type, regex string
}

// TransformRuleSpec defines actions to clean or enrich data.
type TransformRuleSpec struct {
	Field string `json:"field"`
	Rule  string `json:"rule"`  // "cast", "trim", "lower", "upper", "enrich_time", "add_constant"
	Param string `json:"param"` // E.g., "float", "int", "string", value
}

// AggregationSpec defines computed statistics.
type AggregationSpec struct {
	Field   string `json:"field"`             // Field to aggregate
	Func    string `json:"func"`              // "count", "sum", "avg", "min", "max"
	GroupBy string `json:"group_by,omitempty"` // Field to group by
	Target  string `json:"target"`            // Key name in the final results map
}

// ExportTargetSpec represents an output persistence destination.
type ExportTargetSpec struct {
	Type string `json:"type"` // "csv", "json", "db"
	Path string `json:"path"` // File path or table name
}

// Record is the unified payload flowing through the pipeline channels.
type Record struct {
	JobID      string         `json:"job_id"`
	RowID      int64          `json:"row_id"` // to track order
	RawPayload []byte         `json:"raw_payload"`
	ParsedData map[string]any `json:"parsed_data"`
	IsValid    bool           `json:"is_valid"`

	// Keep existing metadata to support processing and error collection
	SourceID   string         `json:"source_id,omitempty"`
	Errors     []string       `json:"errors,omitempty"`
	Timestamp  time.Time      `json:"timestamp"`
}

// JobStatus represents the state of a job run.
type JobStatus string

const (
	StatusPending   JobStatus = "PENDING"
	StatusRunning   JobStatus = "RUNNING"
	StatusCompleted JobStatus = "COMPLETED"
	StatusFailed    JobStatus = "FAILED"
	StatusCancelled JobStatus = "CANCELLED"
)

// JobProgress represents the real-time metrics exposed by the /progress endpoint.
type JobProgress struct {
	JobID            string            `json:"job_id"`
	RecordsProcessed int64             `json:"records_processed"`
	RecordsPending   int64             `json:"records_pending"`
	ErrorCount       int64             `json:"error_count"`
	PercentComplete  float64           `json:"percent_complete"`
	ProcessingRate   float64           `json:"processing_rate"` // records/sec

	// Keep compatibility fields for the frontend dashboard
	Name             string            `json:"name,omitempty"`
	Status           JobStatus         `json:"status,omitempty"`
	TotalRecords     int64             `json:"total_records,omitempty"`
	ProcessedRecords int64             `json:"processed_records,omitempty"`
	FailedRecords    int64             `json:"failed_records,omitempty"`
	StartTime        time.Time         `json:"start_time,omitempty"`
	EndTime          *time.Time        `json:"end_time,omitempty"`
	StageLatencies   map[string]double `json:"stage_latencies_ms,omitempty"`
}

// AggregatedResult is the final computed statistics generated by the Aggregation stage.
type AggregatedResult struct {
	JobID       string                    `json:"job_id"`
	TotalCount  int64                     `json:"total_count"`
	Sums        map[string]float64        `json:"sums"`
	Averages    map[string]float64        `json:"averages"`
	GroupedData map[string]map[string]any `json:"grouped_data"`
}

// Custom double for compatibility if we want simpler floats.
type double = float64

// UnmarshalJSON implements custom unmarshaling to support both new and old config names.
func (j *JobSpec) UnmarshalJSON(data []byte) error {
	type Alias JobSpec
	aux := &struct {
		*Alias
		AggregationSpecs []AggregationSpec `json:"aggregation_specs"`
		Workers          WorkerConfig      `json:"workers"`
	}{
		Alias: (*Alias)(j),
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	if len(j.AggregationTypes) == 0 && len(aux.AggregationSpecs) > 0 {
		j.AggregationTypes = aux.AggregationSpecs
	}
	if j.WorkerPoolSizes.Validation == 0 && j.WorkerPoolSizes.Transformation == 0 {
		if aux.Workers.Validation > 0 || aux.Workers.Transformation > 0 {
			j.WorkerPoolSizes = aux.Workers
		}
	}
	return nil
}

// MarshalJSON implements custom marshaling to serialize both representation properties.
func (j *JobSpec) MarshalJSON() ([]byte, error) {
	type Alias JobSpec
	return json.Marshal(&struct {
		*Alias
		AggregationSpecs []AggregationSpec `json:"aggregation_specs,omitempty"`
		Workers          WorkerConfig      `json:"workers,omitempty"`
	}{
		Alias:            (*Alias)(j),
		AggregationSpecs: j.AggregationTypes,
		Workers:          j.WorkerPoolSizes,
	})
}

